name: acoustic-to-anthropometric
channels:
  - anaconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=py312h06a4308_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - comm=0.2.1=py312h06a4308_0
  - debugpy=1.8.16=py312hbdd6827_0
  - decorator=5.2.1=py312h06a4308_0
  - executing=2.2.1=py312h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ipykernel=6.30.1=py312h06a4308_0
  - ipython=9.5.0=py312h06a4308_0
  - ipython_pygments_lexers=1.1.1=py312h06a4308_0
  - jedi=0.19.2=py312h06a4308_0
  - jupyter_client=8.6.3=py312h06a4308_0
  - jupyter_core=5.8.1=py312h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnsl=2.0.0=h5eee18b_0
  - libsodium=1.0.20=heac8642_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-inline=0.1.7=py312h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py312h06a4308_0
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py312h06a4308_1
  - parso=0.8.4=py312h06a4308_0
  - pexpect=4.9.0=py312h06a4308_0
  - pip=25.2=pyhc872135_1
  - platformdirs=4.3.7=py312h06a4308_0
  - prompt-toolkit=3.0.52=py312h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py312hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.3=py312h06a4308_0
  - pydantic-core=2.41.4=py312h498d7c9_0
  - pygments=2.19.1=py312h06a4308_0
  - python=3.12.12=hd17a9e1_1
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - pyzmq=27.1.0=py312hcf8288c_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py312h06a4308_0
  - six=1.17.0=py312h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=py312h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py312h5eee18b_0
  - tqdm=4.67.1=py312he106c6f_0
  - traitlets=5.14.3=py312h06a4308_0
  - typing-extensions=4.15.0=py312h06a4308_0
  - typing-inspection=0.4.2=py312h06a4308_0
  - typing_extensions=4.15.0=py312h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.13=py312h06a4308_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - annotated-types==0.7.0
      - audeer==2.3.1
      - audformat==1.3.2
      - audinterface==1.3.1
      - audiofile==1.5.1
      - audmath==1.4.4
      - audobject==0.7.12
      - audresample==1.3.5
      - cffi==2.0.0
      - importlib-metadata==8.7.0
      - iso3166==2.1.1
      - iso639-lang==2.6.3
      - opencv-python==4.12.0.88
      - opensmile==2.6.0
      - oyaml==1.0
      - pyarrow==22.0.0
      - pycparser==2.23
      - pydantic==2.12.3
      - zipp==3.23.0