name: deep3d_pytorch
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _pytorch_select=0.2=gpu_0
  - blas=1.0=mkl
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2021.5.30=py36h06a4308_0
  - cffi=1.14.6=py36h400218f_0
  - cuda-version=11.1=hdbd7af8_3
  - cudatoolkit=11.1.1=hb139c0e_13
  - cudnn=8.9.7.29=hbc23b4c_3
  - dataclasses=0.8=pyh787bdff_2
  - freetype=2.13.3=h4a9f257_0
  - future=0.18.2=py36h5fab9bb_3
  - giflib=5.2.2=h5eee18b_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9f=h5ce9db8_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libblas=3.9.0=12_linux64_mkl
  - libcblas=3.9.0=12_linux64_mkl
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.3=he6710b0_2
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblapack=3.9.0=12_linux64_mkl
  - libpng=1.6.50=h2ed474d_0
  - libprotobuf=3.18.3=h6239696_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.5.1=hffd6297_1
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - magma=2.5.4=h5fc5d34_4
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py36h8f6f2f9_0
  - mkl_fft=1.0.10=py36_0
  - mkl_random=1.2.2=py36h84e8a9e_0
  - nccl=2.27.3.1=h03a54cd_0
  - ncurses=6.5=h7934f7d_0
  - ninja-base=1.12.1=hdb19cb5_0
  - numpy=1.19.5=py36hfc0c790_2
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=1.1.1w=h7f8727e_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.21=pyhd3eb1b0_0
  - python=3.6.13=h12debd9_1
  - python_abi=3.6=2_cp36m
  - pytorch=1.9.1=cuda111py36h8a2106e_3
  - pytorch-gpu=1.9.1=cuda111py36h788eb59_3
  - readline=8.3=hc2a1206_0
  - sleef=3.9.0=ha0421bc_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - torchvision=0.10.1=py36cuda111h50ec057_0_cuda
  - typing_extensions=4.1.1=pyh06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==0.15.0
      - anyio==3.6.2
      - asgiref==3.4.1
      - astor==0.8.1
      - astunparse==1.6.3
      - cached-property==1.5.2
      - cachetools==4.2.4
      - charset-normalizer==2.0.12
      - clang==5.0
      - click==8.0.4
      - contextlib2==21.6.0
      - contextvars==2.4
      - cycler==0.11.0
      - decorator==4.4.2
      - dominate==2.9.1
      - fastapi==0.83.0
      - flatbuffers==1.12
      - gast==0.2.2
      - google-auth==1.35.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.48.2
      - h11==0.13.0
      - h5py==3.1.0
      - idna==3.10
      - imageio==2.15.0
      - imageio-ffmpeg==0.5.1
      - immutables==0.19
      - importlib-metadata==4.8.3
      - keras==2.6.0
      - keras-applications==1.0.8
      - keras-preprocessing==1.1.2
      - kiwisolver==1.3.1
      - kornia==0.6.8
      - markdown==3.3.7
      - matplotlib==3.3.4
      - mock==5.2.0
      - networkx==2.5.1
      - ninja==1.11.1.1
      - oauthlib==3.2.2
      - opencv-python==3.4.13.47
      - opt-einsum==3.3.0
      - packaging==21.3
      - pillow==8.4.0
      - pip==21.3.1
      - protobuf==3.19.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydantic==1.9.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pywavelets==1.1.1
      - requests==2.27.1
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-image==0.17.2
      - scipy==1.5.4
      - setuptools==59.5.0
      - six==1.15.0
      - sniffio==1.2.0
      - starlette==0.19.1
      - tensorboard==1.15.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==1.15.0
      - tensorflow-estimator==1.15.1
      - termcolor==1.1.0
      - tifffile==2020.9.3
      - trimesh==3.23.5
      - urllib3==1.26.20
      - uvicorn==0.16.0
      - werkzeug==2.0.3
      - wrapt==1.12.1
      - zipp==3.6.0